### ISSUE TITLE
Numerical suffix is not being handled

### ISSUE THREAD

**Issue by rlfolden** [ralflorent/namefully-dart#4]
I have a grandson named after the 3rd person in his dad's family with same name: eg, "Marty Lee Robbins III"

When I run his name thru namefully, i.e.,  
var nameFully = Namefully("Marty Lee Robbins III");

The "III" shows up in the lastName, not in the suffix

**Comment by ralflorent** [comment]
Thanks, @rlfolden, for reporting this, but there's been a slight misunderstanding. 
Given the name standards used in this utility, you'd need to use another constructor to succeed:

```dart
final name = Namefully.only(
  firstName: 'Marty',
  middleName: ['Lee'],
  lastName: 'Robbins',
  suffix: 'III',
);
``` 

or `Namefully.fromJson(...)`, `Namefully.of(...)`, whichever pleases you.

 You need to dictate each name piece separately because it's non-standard to how the utility interprets a string name. For a 4-piece element name, for example,  `namefully` understands it will operate on a prefix, first, middle and last name.

> Side note: check out these [test cases](https://github.com/ralflorent/namefully-dart/blob/69cbe235570f81a1c9fe4db188908b203dfbd107/test/utils_test.dart#L19) for more details.
