### ISSUE TITLE
Last name parsing unexpected when Prefix First Last Suffix as raw input

### ISSUE THREAD

**Issue by kylehayes** [ralflorent/namefully-dart#5]
**Describe the bug**
When raw input is in the format Prefix First Last Suffix, e.g. `Mr John Smith Ph.D`, `.last` yields `Ph.D`.

**Steps to reproduce**

1. Use this name `Mr John Smith Ph.D`
2. Include this config -> default config
3. Call this function or method `.last`

**Expected behavior**
I would expect the last name to be `Smith` in this case.

**Dev environment (please complete the following information):**

- Platform: Dart VM
- OS: macOS
- SDK: Dart 3.4.1
- Version: 3.4.1

**Comment by ralflorent** [comment]
Thanks, @kylehayes , for reporting this. 

This is an expected behavior. If you take a look at this reference page: https://pub.dev/documentation/namefully/latest/namefully/NameIndex-class.html, you'll notice the parsing for raw string content corresponds strictly to this pattern: `4 elements: prefix firstName middleName lastName`. That's because suffixes have the lowest relevance score.

If `suffix` is relevant to your use case, you may achieve this by using a named constructor: `Namefully.of()`,  `Namefully.fromJson()`, or `Namefully.only()`. For example:

```dart
import 'package:namefully/namefully.dart';

void main() {
  final name = Namefully.only(
    prefix: 'Mr',
    firstName: 'John',
    lastName: 'Smith',
    suffix: 'Ph.D',
  );

  print(name.last); // Smith
  print(name.full); // Mr John Smith Ph.D
  print(name.birth); // John Smith
  print(name.suffix); // Ph.D
}
```

Another more complex way of achieving this is by redefining the relevance score in `NameIndex` using your own `Parser`. 
Hopefully this is clear and helpful.

**Comment by kylehayes** [comment]
I considered that might be your response once I further realized that the library really is set to a specific standard. I'm looking for something that can shape unstructured name inputs without knowing what names will be provided.

I've since implemented a basic parser for my use case. Thank you, though!
